apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xxmz8dbtk-go 
  janus-idp.io/tekton: xxmz8dbtk-go
  backstage.io/kubernetes-id: xxmz8dbtk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xxmz8dbtk-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  